
export const IMAGE_DIRECTORY = "http://localhost:5050/images/"

export const SESSION_USER = "HELPERZZZ_ADMIN_USER"

//REDUCERS
export const CATEGORY_REDUCER = "CATEGORY_REDUCER"
export const USER_REDUCER = "USER_REDUCER"
export const BLOG_REDUCER = "BLOG_REDUCER"
export const COST_GUIDE_REDUCER = "COST_GUIDE_REDUCER"
export const CONTRACTOR_REDUCER = "CONTRACTOR_REDUCER"


//CATEGORY
export const ALL_CATEGORIES = "ALL_CATEGORIES"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const STATUS_CATEGORY = "STATUS_CATEGORY"
export const FEATURE_CATEGORY = "FEATURE_CATEGORY"


//USERS
export const ALL_USERS = "ALL_USERS"
export const CREATE_USER = "CREATE_USER"
export const DELETE_USER = "DELETE_USER"
export const STATUS_USER = "STATUS_USER"
export const FEATURE_USER = "FEATURE_USER"


//BLOGS
export const ALL_BLOGS = "ALL_BLOGS"
export const CREATE_BLOG = "CREATE_BLOG"
export const DELETE_BLOG = "DELETE_BLOG"
export const STATUS_BLOG = "STATUS_BLOG"
export const FEATURE_BLOG = "FEATURE_BLOG"


//CONTRACTORS
export const ALL_CONTRACTORS = "ALL_CONTRACTORS"
export const CREATE_CONTRACTOR = "CREATE_CONTRACTOR"
export const DELETE_CONTRACTOR = "DELETE_CONTRACTOR"
export const STATUS_CONTRACTOR = "STATUS_CONTRACTOR"
export const FEATURE_CONTRACTOR = "FEATURE_CONTRACTOR"


//COST GUIDES
export const ALL_COSTGUIDES = "ALL_COSTGUIDES"
export const CREATE_COSTGUIDE = "CREATE_COSTGUIDE"
export const DELETE_COSTGUIDE = "DELETE_COSTGUIDE"
export const STATUS_COSTGUIDE = "STATUS_COSTGUIDE"
export const FEATURE_COSTGUIDE = "FEATURE_COSTGUIDE"
