
export const IMAGE_PATH = "https://api.helperzz.com/public/uploads/"

export const SESSION_USER = "HELPERZZZ_ADMIN_USER"

//REDUCERS
export const CATEGORY_REDUCER = "CATEGORY_REDUCER"
export const SUBCATEGORY_REDUCER = "SUBCATEGORY_REDUCER"
export const USER_REDUCER = "USER_REDUCER"
export const BLOG_REDUCER = "BLOG_REDUCER"
export const COST_GUIDE_REDUCER = "COST_GUIDE_REDUCER"
export const CONTRACTOR_REDUCER = "CONTRACTOR_REDUCER"
export const TESTIMONIAL_REDUCER = "TESTIMONIAL_REDUCER"
export const REQUESTS_REDUCER = "REQUESTS_REDUCER"
export const CUSTOMER_REDUCER = "CUSTOMER_REDUCER"


//CATEGORY
export const ALL_CATEGORIES = "ALL_CATEGORIES"
export const SINGLE_CATEGORY = "SINGLE_CATEGORY"
export const ACTIVE_CATEGORIES = "ACTIVE_CATEGORIES"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const STATUS_CATEGORY = "STATUS_CATEGORY"
export const FEATURE_CATEGORY = "FEATURE_CATEGORY"


//SUBCATEGORY
export const ALL_SUBCATEGORIES = "ALL_SUBCATEGORIES"
export const SINGLE_SUBCATEGORY = "SINGLE_SUBCATEGORY"
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY"
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"
export const STATUS_SUBCATEGORY = "STATUS_SUBCATEGORY"


//TESTIMONIAL
export const ALL_TESTIMONIALS = "ALL_TESTIMONIALS"
export const SINGLE_TESTIMONIAL = "SINGLE_TESTIMONIAL"
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL"
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL"
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const STATUS_TESTIMONIAL = "STATUS_TESTIMONIAL"


//SEVICE REQUESTS
export const ALL_REQUESTS = "ALL_REQUESTS"
export const SINGLE_REQUEST = "SINGLE_REQUEST"
export const ASSIGN_CONTRACTOR = "ASSIGN_CONTRACTOR"


//CUSTOMERS
export const ALL_CUSTOMERS = "ALL_CUSTOMERS"


//USERS
export const ALL_USERS = "ALL_USERS"
export const SINGLE_USER = "SINGLE_USER"
export const CREATE_USER = "CREATE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const STATUS_USER = "STATUS_USER"
export const FEATURE_USER = "FEATURE_USER"


//BLOGS
export const ALL_BLOGS = "ALL_BLOGS"
export const SINGLE_BLOG = "SINGLE_BLOG"
export const CREATE_BLOG = "CREATE_BLOG"
export const UPDATE_BLOG = "UPDATE_BLOG"
export const DELETE_BLOG = "DELETE_BLOG"
export const STATUS_BLOG = "STATUS_BLOG"
export const FEATURE_BLOG = "FEATURE_BLOG"


//CONTRACTORS
export const ALL_CONTRACTORS = "ALL_CONTRACTORS"
export const SINGLE_CONTRACTOR = "SINGLE_CONTRACTOR"
export const ACTIVE_CONTRACTORS = "ACTIVE_CONTRACTORS"
export const ASSIGNED_CONTRACTORS = "ASSIGNED_CONTRACTORS"
export const CREATE_CONTRACTOR = "CREATE_CONTRACTOR"
export const CREATE_AFFILIATION = "CREATE_AFFILIATION"
export const CREATE_AWARD = "CREATE_AWARD"
export const CREATE_BADGE = "CREATE_BADGE"
export const CREATE_PROJECT = "CREATE_PROJECT"
export const UPDATE_CONTRACTOR = "UPDATE_CONTRACTOR"
export const CREATE_DETAILS = "CREATE_DETAILS"
export const UPDATE_DETAILS = "UPDATE_DETAILS"
export const DETAILS_CONTRACTOR = "DETAILS_CONTRACTOR"
export const DELETE_CONTRACTOR = "DELETE_CONTRACTOR"
export const STATUS_CONTRACTOR = "STATUS_CONTRACTOR"
export const FEATURE_CONTRACTOR = "FEATURE_CONTRACTOR"


//COST GUIDES
export const ALL_COSTGUIDES = "ALL_COSTGUIDES"
export const SINGLE_COSTGUIDE = "SINGLE_COSTGUIDE"
export const CREATE_COSTGUIDE = "CREATE_COSTGUIDE"
export const UPDATE_COSTGUIDE = "UPDATE_COSTGUIDE"
export const DELETE_COSTGUIDE = "DELETE_COSTGUIDE"
export const STATUS_COSTGUIDE = "STATUS_COSTGUIDE"
export const FEATURE_COSTGUIDE = "FEATURE_COSTGUIDE"
